### PR TITLE
Hide redundant 'but it feels like'

### PR DESCRIPTION
**Pull request by thaJeztah**
Because, well...

    The temperature is 58.68°F, but it feels like 58.68°F

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @jfrazelle :sunny:

**Comment by jfrazelle** [comment]
Nice!!!

**Comment by thaJeztah** [comment]
Thanks Jess! More coming, when I get back home nice simple code to hack a bit on :smile:

**Comment by jfrazelle** [comment]
Cool!!!!

**Comment by thaJeztah** [comment]
SFO now, flight looks to be delayed, but there's WiFi, so feels like 127.0.0.1

**Pull request merged**
